export const penObj = [
  {
    title: '1',
    desc: '그냥볼펜',
    level: '5',
    ballPenName: 'weapon1',
    Gold: 0,
  },
  {
    title: '2',
    desc: '하이테크입니다.',
    level: '5',
    ballPenName: 'weapon2',
    Gold: 10000,
  },
  {
    title: '3',
    desc: '만년필입니다.',
    level: '5',
    ballPenName: 'weapon3',
    Gold: 100000,
  },
  {
    title: '4',
    desc: '기념품입니다.',
    level: '5',
    ballPenName: 'weapon4',
    Gold: 10000,
  },
  {
    title: '5',
    desc: '기념품입니다.',
    level: '5',
    ballPenName: 'weapon5',
    Gold: 10000000,
  },
  {
    title: '6',
    desc: '기념품입니다.',
    level: '5',
    ballPenName: 'weapon4',
    Gold: 10000,
  },
  {
    title: '7',
    desc: '기념품입니다.',
    level: '5',
    ballPenName: 'weapon5',
    Gold: 10000000,
  },
  {
    title: '8',
    desc: '기념품입니다.',
    level: '5',
    ballPenName: 'weapon4',
    Gold: 10000,
  },
  {
    title: '9',
    desc: '기념품입니다.',
    level: '5',
    ballPenName: 'weapon5',
    Gold: 10000000,
  },
  {
    title: '10',
    desc: '기념품입니다.',
    level: '5',
    ballPenName: 'weapon4',
    Gold: 10000,
  },
  {
    title: '11',
    desc: '기념품입니다.',
    level: '5',
    ballPenName: 'weapon5',
    Gold: 10000000,
  },
  {
    title: '12',
    desc: '기념품입니다.',
    level: '5',
    ballPenName: 'weapon4',
    Gold: 10000,
  },
  {
    title: '13',
    desc: '기념품입니다.',
    level: '5',
    ballPenName: 'weapon5',
    Gold: 10000000,
  },
  {
    title: '14',
    desc: '기념품입니다.',
    level: '5',
    ballPenName: 'weapon5',
    Gold: 10000000,
  },
  {
    title: '15',
    desc: '기념품입니다.',
    level: '5',
    ballPenName: 'weapon5',
    Gold: 10000000,
  },
  {
    title: '16',
    desc: '기념품입니다.',
    level: '5',
    ballPenName: 'weapon5',
    Gold: 10000000,
  },
  {
    title: '17',
    desc: '기념품입니다.',
    level: '5',
    ballPenName: 'weapon5',
    Gold: 10000000,
  },
  {
    title: '18',
    desc: '기념품입니다.',
    level: '5',
    ballPenName: 'weapon18',
    Gold: 10000000,
  },
  {
    title: '19',
    desc: '기념품입니다.',
    level: '5',
    ballPenName: 'weapon5',
    Gold: 10000000,
  },
];
