CREATE TABLE `users` (
   `Index` int NOT NULL AUTO_INCREMENT,
   `Id` varchar(45) COLLATE utf8mb4_bin NOT NULL,
   `Password` varchar(450) COLLATE utf8mb4_bin NOT NULL,
   `Salt` varchar(450) COLLATE utf8mb4_bin NOT NULL,
   `Level` int DEFAULT '1',
   `Exp` int DEFAULT '0',
   `BasicDamage` int DEFAULT '100',
   `BasicHp` int DEFAULT '100',
   `WeaponDamage` int DEFAULT '5',
   `WeaponHp` int DEFAULT '5',
   `EquipDamage` int DEFAULT '0',
   `EquipHp` int DEFAULT '0',
   `Gold` bigint DEFAULT '100',
   `Inventory` varchar(45) COLLATE utf8mb4_bin DEFAULT NULL,
   `PenCount` int DEFAULT '0',
   `HuntingCount` int DEFAULT '0',
   `SkillPoint` int DEFAULT '0',
   `UpGoldAll` int DEFAULT '0',
   `UpGoldHunt` int DEFAULT '0',
   `UpGoldPen` int DEFAULT '0',
   `DoubleAttack` varchar(45) COLLATE utf8mb4_bin DEFAULT '0',
   `Grabber` varchar(45) COLLATE utf8mb4_bin DEFAULT '0',
   `DungeonFloor` int NOT NULL DEFAULT '1',
   PRIMARY KEY (`Index`)
 ) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin