CREATE TABLE `users` (
   `Index` int NOT NULL AUTO_INCREMENT,
   `Id` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
   `Password` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
   `Salt` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
   `Level` int NOT NULL DEFAULT '1',
   `BasicDamage` int NOT NULL DEFAULT '100',
   `BasicHp` int NOT NULL DEFAULT '100',
   `WeaponDamage` int NOT NULL DEFAULT '5',
   `WeaponHp` int NOT NULL DEFAULT '5',
   `EquipDamage` int NOT NULL DEFAULT '0',
   `EquipHp` int DEFAULT '0',
   `Gold` bigint NOT NULL DEFAULT '0',
   `Inventory` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
   `PenCount` int NOT NULL DEFAULT '0',
   `HuntingCount` int NOT NULL DEFAULT '0',
   `UpGoldAll` int NOT NULL DEFAULT '0',
   `UpGoldHunt` int NOT NULL DEFAULT '0',
   `UpGoldPen` int NOT NULL DEFAULT '0',
   `UpWeaponDamage` int NOT NULL DEFAULT '0',
   `UpWeaponHp` int NOT NULL DEFAULT '0',
   `DoubleAttack` int NOT NULL DEFAULT '0',
   `Grabber` int NOT NULL DEFAULT '0',
   `Exp` int NOT NULL DEFAULT '0',
   `DungeonFloor` int NOT NULL DEFAULT '1',
   `BetterPen` int NOT NULL DEFAULT '0',
   `SkillPoint` int NOT NULL DEFAULT '20',
   `EquipBallpen` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT 'weapon1',
   `BuyBallpenList` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT 'weapon1',
   `UpMaxHp` int DEFAULT '0',
   `DungeonPenSpeed` int DEFAULT '1',
   `PenGamePenSpeed` int DEFAULT '1',
   PRIMARY KEY (`Index`)
 ) ENGINE=InnoDB AUTO_INCREMENT=80 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='유저 테이블\n유저번호 / 닉네임 / 비밀번호 /레벨 / 기본 공격력 / 기본 체력 / 무기 공격력 / 방어구 체력 / 장착중인 무기 / 장착중인 방어구 / 화폐 / 각 스킬의 레벨 / 가지고 있는 아이템 / 볼펜 돌린 횟수 / 사냥 횟수'