CREATE TABLE `users` (
   `Index` int NOT NULL AUTO_INCREMENT,
   `Id` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL,
   `Password` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL,
   `Salt` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL,
   `Level` int DEFAULT '1',
   `BasicDamage` int DEFAULT '100',
   `BasicHp` int DEFAULT '100',
   `WeaponDamage` int DEFAULT '5',
   `WeaponHp` int DEFAULT '5',
   `EquipDamage` int DEFAULT '0',
   `EquipHp` int DEFAULT '0',
   `Gold` bigint DEFAULT '0',
   `Inventory` varchar(45) COLLATE utf8mb4_bin DEFAULT NULL,
   `PenCount` int DEFAULT '0',
   `HuntingCount` int DEFAULT '0',
   `UpGoldAll` int DEFAULT '0',
   `UpGoldHunt` int DEFAULT '0',
   `UpGoldPen` int DEFAULT '0',
   `UpWeaponDamage` int DEFAULT '0',
   `UpWeaponHp` int DEFAULT '0',
   `DoubleAttack` int DEFAULT '0',
   `Grabber` int DEFAULT '0',
   `Exp` int DEFAULT '0',
   `DungeonFloor` int DEFAULT '1',
   `BetterPen` int DEFAULT '0',
   `SkillPoint` int DEFAULT '20',
   PRIMARY KEY (`Index`)
 ) ENGINE=InnoDB AUTO_INCREMENT=47 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='유저 테이블\n유저번호 / 닉네임 / 비밀번호 /레벨 / 기본 공격력 / 기본 체력 / 무기 공격력 / 방어구 체력 / 장착중인 무기 / 장착중인 방어구 / 화폐 / 각 스킬의 레벨 / 가지고 있는 아이템 / 볼펜 돌린 횟수 / 사냥 횟수'