name: pull repo
on:
  push:
    branches:
      - master
jobs:
  build:
    name: pull repo
    runs-on: ubuntu-latest
    steps:
    - name: git pull repository
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          sudo su
          cd NoteGame
          git pull
          npm i
          npm run build
          npx pm2 kill
          npx pm2 install typescript
          npx pm2 start server/app.ts
          
        
          
